name: qlx-hfp-ci
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:
    inputs:
      force:
        description: "Run manually"
        required: false
        default: "true"

jobs:
  test-and-sts:
    runs-on: ubuntu-latest
    env:
      ARGON2_TIME_COST: "2"
      ARGON2_MEMORY_KIB: "65536"
      ARGON2_PARALLELISM: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install deps
        run: python -m pip install -r requirements.txt
      - name: Unit tests
        run: make test

      - name: STS sha512
        run: |
          mkdir -p artifacts
          python src/qlx_sts_min.py --n-bits 200000 --whiten sha512 --json-out artifacts/sts_sha512.json

      - name: STS vn
        run: python src/qlx_sts_min.py --n-bits 200000 --whiten vn --json-out artifacts/sts_vn.json

      - name: Guard min_p
        run: |
          python - << "PY"
import json, sys
ok = True
for path in ["artifacts/sts_sha512.json","artifacts/sts_vn.json"]:
    r = json.load(open(path))
    mp = r["summary"]["min_p"]
    if not (mp >= 0.012 and r["summary"]["all_pass"]):
        print("Guard failed:", path, "min_p", mp)
        ok = False
sys.exit(0 if ok else 2)
PY

      - name: Upload sha512
        uses: actions/upload-artifact@v4
        with:
          name: sts-report-sha512
          path: artifacts/sts_sha512.json
          if-no-files-found: error

      - name: Upload vn
        uses: actions/upload-artifact@v4
        with:
          name: sts-report-vn
          path: artifacts/sts_vn.json
          if-no-files-found: error
