name: qlx-hfp-ci
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:
jobs:
  test-and-sts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: make test
      - name: Run STS mini battery
        run: make sts
