name: qlx-sts-nightly

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch: {}
  push:
    branches: ["**"]

jobs:
  soak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke
        run: echo "nightly smoke ok"
