name: qlx-envelope-v1

on:
  workflow_dispatch: {}
  push:
    branches: ["**"]

jobs:
  envelope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Smoke
        run: echo "envelope smoke ok"
