name: qlx-security-audit

on:
  workflow_dispatch: {}
  push:
    branches: ["**"]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install pip-audit
        run: python -m pip install --upgrade pip && python -m pip install pip-audit

      - name: Run pip-audit (requirements.txt)
        run: |
          mkdir -p artifacts
          pip-audit -r requirements.txt -f json -o artifacts/pip_audit.json || true
          pip-audit -r requirements.txt -f markdown -o artifacts/pip_audit.md || true

      - name: Upload security audit
        uses: actions/upload-artifact@v4
          retention-days: 30
        with:
          name: security-audit
          path: |
            artifacts/pip_audit.json
            artifacts/pip_audit.md
