name: qlx-sts-weekly

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}

jobs:
  weekly-sts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install deps
        run: python -m pip install -r requirements.txt

      - name: STS sha512 (2e6) – seed qlx-demo-seed-phi369
        run: |
          mkdir -p artifacts/weekly
          python src/qlx_sts_min.py --seed "qlx-demo-seed-phi369" --n-bits 2000000 --whiten sha512 --json-out artifacts/weekly/sts_2e6_sha512.json

      - name: STS vn (5e5) – seed qlx-demo-seed-phi369
        run: |
          python src/qlx_sts_min.py --seed "qlx-demo-seed-phi369" --n-bits 500000 --whiten vn --json-out artifacts/weekly/sts_5e5_vn.json

      - name: Build weekly summary
        run: >
          python -c "import json, pathlib; b=pathlib.Path('artifacts/weekly'); 
          sha=json.load(open(b/'sts_2e6_sha512.json'))['summary']; 
          vn=json.load(open(b/'sts_5e5_vn.json'))['summary']; 
          out={'seed':'qlx-demo-seed-phi369','sha512_2e6':sha,'vn_5e5':vn}; 
          json.dump(out, open(b/'summary.json','w'), indent=2)"

      - name: Upload weekly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sts-weekly
          path: |
            artifacts/weekly/sts_2e6_sha512.json
            artifacts/weekly/sts_5e5_vn.json
            artifacts/weekly/summary.json
          retention-days: 30
